#!/usr/bin/env node
//const conf = require('/home/pi/.config/get-weather.json');
const fetch = require('node-fetch');
//const iconMap = require('./weather-icon-map');
fetch(`https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22moscow%22)%20and%20u%3D'c'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys`)
.then(res => res.json())
.then(res => res.query.results.channel.item.condition)
.then(cond => ({
	//time_delta: (new Date(cond.dt_txt + '+00:00') - Date.now()) / (1000 * 60 * 60),
	//rain: cond.rain,
	//description: cond.weather[0].description,
	//icon: iconMap['wi-owm-day-' + cond.weather[0].id], //cond.weather[0].icon,
	temp: cond.temp,
	description: cond.description,
}))
.then(json => console.log(JSON.stringify(json)))
.catch(e => {console.error(e);process.exit(1); });
